# Site
name: "Internet Daily Deals "
title: "Internet Daily Deals "
description: "We strive to help our readers find the best deals on quality products and services"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'G-6XCXLHK0WG'
disqus: 'demowebsite'
mailchimp-list: 'https://club.us5.list-manage.com/subscribe/post?u=a839bbbdc37891b132e7db91c&amp;id=d151dabdf3'
include: ["_pages"]
permalink: /:title/
email: press@internetdailydeals.com

# Authors
authors:

  jeff:
    name: Jeff
    display_name: Jeff    
    avatar: 'assets/images/avatar.png'
    email: mrgabonijeff@gmail.com
    gravatar: 298224aa0a009468d621d71b80cf8395
    web: https://www.webdevpl.us
    facebook: https://facebook.com/iamthenewking
    description: "Web developer/designerğŸš€ turned SEO ğŸŒ / Technical writer ğŸ“"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-4201549272943840"
adsense-data-ad-slot: "3113137593"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"




# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
